--- 
abstract: use a class to back C<< $c->* >>
author: Jonathan Rockway C<< jrockway@cpan.org >>
build_requires: 
  Catalyst::Runtime: 0
  Class::Accessor: 0
  Test::More: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-HashClass
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Utils: 0
  Class::Data::Inheritable: 0
  NEXT: 0
version: 0.01
